---
name: Lint Awesome List

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
        with:
          fetch-depth: 0
=======

<<<<<<< HEAD
>>>>>>> 6760a9f (Add GitHub Super Linter (#20))
      - run: npx awesome-lint
=======
      - uses: taiki-e/install-action@just

      - run: just awesome-lint
>>>>>>> 9c3215b (Help you to contribute (#105))
        shell: bash
