name: Lint Awesome List
on: [push, pull_request,workflow_dispatch]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx awesome-lint
        shell: bash
