---
name: Lint content only

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@just

      - run: just configure
        shell: bash

      - run: just awesome-lint
        shell: bash

      - run: just textlint-titlecase
        shell: bash
